jvalue/jayvee

.github/workflows/gh-pages.yaml
apps/docs/project.json

Waiting for making repository public. Otherwise I can't access the options to configure GH Pages (switch `source` to `GitHub Actions`.

Deploy Docs to GitHub Pages

---

.github/workflows/ci.yaml
apps/language-server-web-worker/src/main.ts
apps/vs-code-extension/src/language-server.ts
libs/extensions/rdbms/exec/src/extension.ts
libs/extensions/std/exec/src/extension.ts
libs/extensions/tabular/exec/src/extension.ts
libs/extensions/tabular/exec/src/lib/cell-writer-executor.ts

I noticed that linting warnings are ignored by the CI. So this PR changes the CI setup to disallow linting warnings.
Also fixes some linting warnings that accumulated over time.

Disallow linting warnings in CI

---

apps/docs/docs/user/intro.md

Closes #211. 
Adds the missing parts for installation instructions: the troubleshooting / known issues / FAQ part.

Add troubleshooting section to intro.md docs

---

apps/docs/docs/user/core-concepts.md

Aims to further improve the documentation about core concepts.

Improve core concepts docs

---

.github/workflows/cla.yaml

Preparation for #259 
Followed these instructions: <https://github.com/cla-assistant/cla-assistant#can-i-allow-bot-user-contributions>

Allow dependabot in CLA workflow

---

apps/docs/docs/user/runtime-parameters.md
apps/docs/docs/user/runtime-parameters.md.license

Add docs for runtime parameters

---

apps/docs/docs/user/constraint-types/.gitignore
apps/docs/docs/user/constraint-types/_category_.json
apps/docs/docs/user/constraint-types/_category_.json.license
apps/docs/generator/src/main.ts
apps/docs/generator/src/user-doc-generator.ts
libs/language-server/src/lib/constraint/allowlist-constraint-meta-inf.ts
libs/language-server/src/lib/constraint/denylist-constraint-meta-inf.ts
libs/language-server/src/lib/constraint/length-constraint-meta-inf.ts
libs/language-server/src/lib/constraint/range-constraint-meta-inf.ts
libs/language-server/src/lib/constraint/regex-constraint-meta-inf.ts
libs/language-server/src/lib/docs/jayvee-doc-generator.ts
libs/language-server/src/lib/meta-information/constraint-meta-inf.ts
libs/language-server/src/lib/meta-information/index.ts

Constraint Docs Generation

---

example/cars.jv
example/gas.jv
libs/execution/src/lib/types/io-types/sheet.ts
libs/extensions/tabular/exec/src/lib/cell-writer-executor.ts
libs/extensions/tabular/lang/src/lib/cell-writer-meta-inf.ts
libs/language-server/src/lib/ast/wrappers/cell-range-wrapper.ts

Extend cell writer to support multiple cell writes

---

.github/ISSUE_TEMPLATE/rfc.md
.github/ISSUE_TEMPLATE/rfc.md.license

We can  track upcoming RFCs like this. For example, #280 brought up two further potential RFCs that should be tracked somewhere.

Issue Template for RFCs

---

libs/extensions/std/exec/src/http-extractor-executor.ts

Add support for HTTP protocol

---

libs/extensions/tabular/exec/src/lib/table-interpreter-executor.ts

Log invalid values

---

rfc/0010-constraint-expressions/README.md

Here is the rendered markdown for better reading experience:
https://github.com/jvalue/jayvee/tree/rfc-0010-expression-constraints/rfc/0010-constraint-expressions

RFC 0010 - Expressions as Constraints

---

rfc/0002-mobility-extension/README.md
rfc/0006-gtfs-rt-support/README.md

Changed status of RFC0006 to accepted and linked implementations for GTFS/GTFS-RT.

Changed status of RFC0006 to accepted and linked implementations for GTFS

---

apps/docs/docs/dev/01-intro.md

Once again, please let me know whether something is missing or hard to understand.

Add introduction for developer docs

---

README.md

Add link to contribution guide

---

libs/extensions/tabular/lang/src/lib/table-interpreter-meta-inf.ts

Fix `oftype` keyword in `TabeInterpreter` docs

---

apps/docs/docs/user/transforms.md
apps/docs/docs/user/transforms.md.license

Add user docs for transforms

---

libs/language-server/src/lib/validation/validation-util.ts

Add simplification hints for sub-expressions

---

README.md

Updates the root `README.md` file, so it features the most recent examples.

Update examples in root README

---

apps/docs/docs/user/intro.md

closes #293, I did not get the EEXISTS error anymore.

Added explicit docs how to update the interpreter

---

apps/docs/docs/user/intro.md

I was notified about the missing word by a student ;). I was using the GitHub in place editing, I'm not sure what the troubleshooting change is about.

Grammar fixes for introduction

---

libs/extensions/rdbms/lang/src/lib/sqlite-loader-meta-information.ts
libs/extensions/std/lang/src/archive-interpreter-meta-inf.ts
libs/extensions/std/lang/src/file-picker-meta-inf.ts

Added some examples and cleaned up docs for blocks along the GTFS-file handling path.

Improve documentation of blocks in GTFS pipelines

---

libs/language-server/src/lib/constraint/range-constraint-meta-inf.ts

closes #364 , merged to main because it concerns the latest release.

Fixed error in RangeConstraint, example 2

---

CONTRIBUTING.md
README.md

I was looking for the up-to-date RFC process and it is surprisingly hard to find from the main README.md

Highlight how to contribute and Link RFC process

---

apps/docs/docs/user/core-concepts.md
apps/docs/docs/user/expressions.md
example/electric-vehicles.jv
libs/language-server/src/grammar/expression.langium
libs/language-server/src/lib/ast/expressions/evaluators/in-operator-evaluator.ts
libs/language-server/src/lib/ast/expressions/operator-registry.ts
libs/language-server/src/lib/ast/expressions/type-computers/in-operator-type-computer.ts
libs/language-server/src/lib/ast/expressions/type-inference.ts

Introduces an `in` operator that checks for element inclusion in an array.

In Operator

---

libs/extensions/std/lang/src/file-picker-meta-inf.ts

Update docs to be in line with working code

---

libs/language-server/src/lib/completion/jayvee-completion-provider.ts

Introduces auto-completion for valuetype definitions:
[Screencast from 07-17-2023 08:45:17 PM.webm](https://github.com/jvalue/jayvee/assets/28054628/989a4c6a-02e3-4454-88ed-295cf54e2623)
Unfortunately, it is not that easy for `ValuetypeAssigments`, e.g., found in the `TableInterpreter` block. Probably requires a refactoring of the ast structure as the completion provider does not jump into there with the right ast node.

Auto-completion for Valuetype Definitions

---

libs/interpreter-lib/src/interpreter.ts

Closes #446.
Should lead to a new release.

runPipeline returns ExitCode.FAILURE on error

---

README.md
apps/docs/docs/user/intro.md

Aligns the decription of Jayvee with the one we use on GitHub.
Closes #483.

Update Jayvee description

---

libs/language-server/src/lib/validation/checks/block-definition.ts
libs/language-server/src/stdlib/CSVFileInterpreter.jv
libs/language-server/src/stdlib/GTFSExtractor.jv

WIP: 495 fix pipe warning composite blocktype

---

.github/workflows/cla.yaml

closes #501 
Documentation for CI file: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-run-job-for-specific-repository

Skip CLA Assistant on forks

---

libs/language-server/src/grammar/main.langium
libs/language-server/src/lib/lsp/jayvee-completion-provider.ts
libs/language-server/src/lib/lsp/jayvee-definition-provider.ts
libs/language-server/src/lib/lsp/jayvee-scope-provider.ts
libs/language-server/src/lib/validation/checks/import-definition.ts

Adds syntax `import { Element as Alias } from 'path';`

Import Aliases

---

apps/interpreter/src/current-dir.ts
apps/interpreter/src/examples-smoke-test.spec.ts
apps/interpreter/src/parse-only.spec.ts
apps/interpreter/src/run-action.ts
libs/interpreter-lib/src/interpreter.ts
libs/interpreter-lib/src/parsing-util.ts

Configure interpreter to use current directory as workdir

---

libs/extensions/tabular/exec/src/lib/xlsx-interpreter-executor.ts

Fix import to exceljs library

---

libs/execution/src/lib/blocks/block-executor.ts
libs/execution/src/lib/blocks/composite-block-executor.ts
libs/execution/src/lib/util/mermaid-util.ts
libs/interpreter-lib/src/interpreter.spec.ts
libs/interpreter-lib/src/interpreter.ts
package-lock.json
package.json

Closes #654.
This PR assigns classes to various graph elements:
- Normal block gets the ''block' class and its blocktype as a class
- Composite blocks get the ''composite-block' class
- Edges get the "edge" class
Additionally graphs can be styled using [existing mermaid configuration options](https://mermaid.js.org/intro/syntax-reference.html#configuration).

Graph style

---

libs/extensions/std/exec/src/http-extractor-executor.ts

This PR adds a simple terminal output to `HTTPExtractor` that reports the current download progress.
e.g.
```
[HTTPExtractor] Downloaded 35MB out of 102MB -- 34.3%
```
This was tested with the pipline from #527

 [FEATURE] Report download progress

---

rfc/0017-error-values/README.md

This RFC introduces a rudimentary form of error handling.
Suggestions welcome!

[RFC] 0017 error values

---

libs/language-server/src/lib/lsp/jayvee-completion-provider.ts

This PR adds a completion suggestion for value type properties.
Screenshot from VSCode:
Known issues:
- Assume this line `constraint capitalized: OnlyCapitalLettersAndDigits on id;`. Deleting `OnlyCapitalLettersAndDigits` and requesting a completion does not trigger the `completionFor` method.

[FEATURE] Add completion for value type constraint references
