jvalue/jayvee

apps/interpreter/src/interpreter.ts
Closes #251. Adds tracking and logging the execution duration of a pipeline and its blocks.
```
> nx run interpreter:run -d example/cars.jv
[CarsPipeline] Overview:
Blocks (6 blocks with 5 pipes):
-> CarsExtractor (HttpExtractor)
-> CarsTextFileInterpreter (TextFileInterpreter)
-> CarsCSVInterpreter (CSVInterpreter)
-> NameHeaderWriter (CellWriter)
-> CarsTableInterpreter (TableInterpreter)
-> CarsLoader (SQLiteLoader)
[CarsExtractor] Fetching raw data from https://gist.githubusercontent.com/noamross/e5d3e859aa0c794be10b/raw/b999fb4425b54c63cab088c0ce2c0d6ce961a563/cars.csv
[CarsExtractor] Successfully fetched raw data
[CarsExtractor] Execution duration: 394 ms.
[CarsTextFileInterpreter] Decoding file content using encoding "utf-8"
[CarsTextFileInterpreter] Splitting lines using line …
```
=> Execution time logging

libs/execution/src/lib/execution-context.ts, libs/execution/src/lib/types/valuetypes/atomic-valuetype.ts, libs/extensions/std/lang/src/text-line-deleter-meta-inf.ts, libs/extensions/tabular/lang/src/lib/column-deleter-meta-inf.ts, libs/extensions/tabular/lang/src/lib/row-deleter-meta-inf.ts, libs/extensions/tabular/lang/src/lib/table-interpreter-meta-inf.ts, libs/language-server/src/grammar/expression.langium, libs/language-server/src/grammar/property.langium, libs/language-server/src/grammar/terminal.langium, libs/language-server/src/lib/ast/collection-util.ts, libs/language-server/src/lib/ast/model-util.ts, libs/language-server/src/lib/constraint/allowlist-constraint-meta-inf.ts, libs/language-server/src/lib/constraint/denylist-constraint-meta-inf.ts, libs/language-server/src/lib/constraint/range-constraint-meta-inf.ts, libs/language-server/src/lib/jayvee-module.ts, libs/language-server/src/lib/validation/validation-registry.ts, libs/language-server/src/lib/validation/validators/expression-validator.ts
Preparation for #213
Allows users to use boolean expressions wherever a boolean value is expected. Introduces the following operators (ordered descending by [precedence](https://en.wikipedia.org/wiki/Order_of_operations)):
- `not`: unary operator to negate a boolean value
- `==` / `!=`: binary operator to check (in)equality
- `xor`: binary operator to compute exclusive OR
- `and`: binary operator to compute AND
- `or`: binary operator to compute OR
Example for a boolean expression: `(not true or false) xor true and true` which evaluates to `true`.
Also adds a diagnostic to propose a simplification for expressions that can be evaluated at compile-time:
=> Introduce boolean expressions

libs/extensions/std/lang/src/gtfs-rt-interpreter-meta-inf.ts, libs/extensions/std/lang/src/text-file-interpreter-meta-inf.ts, libs/extensions/std/lang/src/text-line-deleter-meta-inf.ts, libs/extensions/std/lang/src/text-range-selector-meta-inf.ts, libs/extensions/tabular/lang/src/lib/cell-writer-meta-inf.ts, libs/extensions/tabular/lang/src/lib/column-deleter-meta-inf.ts, libs/extensions/tabular/lang/src/lib/row-deleter-meta-inf.ts, libs/extensions/tabular/lang/src/lib/table-interpreter-meta-inf.ts, libs/language-server/src/lib/constraint/allowlist-constraint-meta-inf.ts, libs/language-server/src/lib/constraint/denylist-constraint-meta-inf.ts, libs/language-server/src/lib/constraint/length-constraint-meta-inf.ts, libs/language-server/src/lib/constraint/range-constraint-meta-inf.ts, libs/language-server/src/lib/meta-information/block-meta-inf.ts, libs/language-server/src/lib/meta-information/constraint-meta-inf.ts, libs/language-server/src/lib/meta-information/meta-inf.ts, libs/language-server/src/lib/validation/checks/block-definition.ts, libs/language-server/src/lib/validation/checks/column-literal.ts, libs/language-server/src/lib/validation/checks/constraint-definition.ts, libs/language-server/src/lib/validation/checks/expression.ts, libs/language-server/src/lib/validation/checks/jayvee-model.ts, libs/language-server/src/lib/validation/checks/pipe-definition.ts, libs/language-server/src/lib/validation/checks/pipeline-definition.ts, libs/language-server/src/lib/validation/checks/property-body.ts, libs/language-server/src/lib/validation/checks/range-literal.ts, libs/language-server/src/lib/validation/checks/regex-literal.ts, libs/language-server/src/lib/validation/checks/valuetype-definition.ts, libs/language-server/src/lib/validation/index.ts, libs/language-server/src/lib/validation/validation-context.ts, libs/language-server/src/lib/validation/validation-registry.ts, libs/language-server/src/lib/validation/validation-util.ts
Introduces a `ValidationContext` class that is provided instead of `ValidationAcceptor` to report diagnostics during validation. More precisely it is a wrapper around the usual `ValidationAcceptor`. The purpose is to allow checking whether errors occurred during validation and use this information to abort the validation early.
The PR also includes a few improvements for existing validation checks.
=> Introduce validation context

libs/language-server/src/grammar/property.langium, libs/language-server/src/grammar/terminal.langium
I noticed that decimal numbers are not parsed correctly:
This PR provides a fix by changing the grammar, so the terminals get recognized correctly.
=> Fix parsing of decimal numbers

apps/vs-code-extension/src/extension.ts, apps/vs-code-extension/src/standard-library-file-system-provider.ts, libs/language-server/src/lib/builtin-library/index.ts, libs/language-server/src/lib/builtin-library/jayvee-standard-library.ts, libs/language-server/src/lib/builtin-library/jayvee-workspace-manager.ts, libs/language-server/src/lib/index.ts, libs/language-server/src/lib/jayvee-module.ts
Preparation for #217 
Adds a builtin Jayvee file `standard.jv` that can serve as a standard library in the future. For now, the file is empty (it only contains a comment, so it has no semantics yet).
In VS Code, when navigating to that file, it is marked as read-only and thus cannot be edited by users.
To accomplish this, I followed this guide from the Langium documentation: https://langium.org/guides/builtin-library/
=> Add an empty standard library

apps/vs-code-extension/src/standard-library-file-system-provider.ts, libs/language-server/src/lib/jayvee-module.ts
Includes a minor improvement suggested [here](https://github.com/langium/langium-website/pull/145) and optimizes the usage of `Buffer` in the VS Code extension.
=> Minor improvements for setup of builtin libraries

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/bug.md.license, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/feature.md.license
#286 overwrote the organization-wide issue templates. I would have hoped that they would just mash together both, but obviously this is not the case.
Copied the organization-wide issue templates here.
=> Feature and Bug Issue Templates

libs/language-server/src/grammar/terminal.langium
Closes #297 
The fix was simple but not so easy to find: the terminal order caused the `REGEX` terminal to be picked over `SINGLE_LINE_COMMENT`. So comments with `/` characters were (I guess partly) tokenized as regexes instead of comments which caused the error. Changing the order fixes the problem:
=> Fix line comment parsing error

libs/language-server/src/grammar/cellrange.langium, libs/language-server/src/grammar/terminal.langium, libs/language-server/src/lib/ast/wrappers/cell-range-wrapper.ts, libs/language-server/src/lib/validation/checks/column-id.ts, libs/language-server/src/lib/validation/validation-registry.ts
Fixes the issue addressed in #290 
The reason was, that the `*` character used for multiplication was also part of the `CELL_RANGE` terminal which lead to conflicts. This refactoring changes the terminal for cell ranges, so it does not consume any `*` characters. The consequence is that internally `B1` is considered a single token (which needs to be split manually) and on the other hand `B*` consists of two separate tokens `B` and `*`. This slightly complicates things but I can't think of a more elegant alternative.
=> Fix operator parsing bug

apps/vs-code-extension/package.json
Follow-up for #296
I noticed that due to the missing `version` field in the `package.json` file, the VS Code extension does not load properly during development (i.e. when pressing F5 to run the extension locally).
To fix this problem, I added a version field with a dummy value. Seems like the version value needs to match the semantic versioning schema.
=> Add dummy version to VS Code extension

apps/docs/docs/dev/05-jayvee-extensions.md
So the docs cope with the latest valuetype refactoring in #317
=> Update usage of valuetypes in extension docs

libs/language-server/src/lib/ast/wrappers/value-type/primitive/index.ts
While working on the documentation, I noticed that the following warnings were logged during `nx run docs:build-generator`:
```
WARNING in ./libs/language-server/src/lib/ast/wrappers/value-type/primitive/index.ts 7:0-75
export 'BooleanValuetype' (reexported as 'BooleanValuetype') was not found in './boolean-valuetype' (possible exports: Boolean, isBooleanValuetype)
WARNING in ./libs/language-server/src/lib/ast/wrappers/value-type/primitive/index.ts 8:0-83
export 'CellRangeValuetype' (reexported as 'CellRangeValuetype') was not found in './cell-range-valuetype' (possible exports: CellRange, isCellRangeValuetype)
WARNING in ./libs/language-server/src/lib/ast/wrappers/value-type/primitive/index.ts 9:0-85
export 'CollectionValuetype' (reexported as 'CollectionValuetype') was not found in …
```
=> Fix exports of valuetype types

.github/workflows/ci.yaml, .github/workflows/publish.yaml, apps/interpreter/project.json, apps/interpreter/src/interpreter.ts, apps/language-server-web-worker/project.json, apps/vs-code-extension/project.json, libs/language-server/project.json, libs/monaco-editor/project.json, package.json
Closes #330
The interpreter now logs stack traces when unexpected errors occur. They use source maps when the interpreter is run with `node --enable-source-maps`.
Unfortunately, I could not find out how to make language server logs use source maps in the VS Code extension. I found out that even in the Langium project itself, the logged stack traces don't have a source map:
```
Error:  TypeError: Cannot read properties of undefined (reading 'localeCompare')
at /home/felix-oq/jvalue/langium/packages/langium-vscode/out/language-server/main.js:12302:54
at Array.sort (<anonymous>)
at sortInterfacesTopologically (/home/felix-oq/jvalue/langium/packages/langium-vscode/out/language-server/main.js:12302:32)
at createAstTypes (/home/felix-oq/jvalue/langium/packages/langium-vscode/out/language-server/ …
```
=> Improve debugging

package-lock.json, package.json
Closes #259 
The remaining issues  seems to be related to docusaurus and updating its version did not resolve the issues. So I solved the security issues by [manually overriding the affected packages](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) with their earliest non-vulnerable versions. Not sure though whether this breaks something in the background (esp. regarding the `got` package since it gets bumped from `9.6.0` to `11.8.5`). With the changes, the docs are still building fine and seem to run without any problems.
**Excerpts from dependabot logs**
For the `trim` package:
```
updater | 2023/06/12 11:25:55 INFO <job_676851473> The latest possible version that can be installed is 0.0.1 because of the following conflicting dependencies:
updater | 
updater | …
```
=> Fix security issues via manual overriding

libs/language-server/src/lib/ast/wrappers/value-type/primitive/collection/index.ts
Fixes the type export in order to avoid warnings during building the documentation app.
=> Fix type export of empty collection

apps/docs/docs/user/core-concepts.md, apps/docs/docs/user/expressions.md, apps/docs/docs/user/expressions.md.license, apps/docs/docs/user/intro.md, apps/docs/docs/user/transforms.md
Minor docs updates I noticed when working on sample solutions for AMSE/SAKI. If we ask students to use transforms (and with transforms also expressions), I'd like to have them documented more explicitly in the user docs.
=> User facing docs for transforms and expressions

libs/extensions/std/lang/src/example-validation.spec.ts
This PR changes how the example validation test discovers the examples to be tested.
It no longer requires a hardcoded array of filenames, but rather lists the example directory and tests all '.jv' files from this directory.
=> Example validation refactoring

libs/language-server/src/lib/constraint/constraint-registry.ts, libs/language-server/src/lib/constraint/meta-inf-example-validation.spec.ts
This PR adds a test that validates the examples of all `ConstraintMetaInformation` that are part of the language-server.
Note: I had to add `getConstraintMetaInf()` inside `constraint-registry.ts` because the existing methods (like `getRegisteredConstraintMetaInformation`) did not work. The reason for that is that `it.each` gets resolved before `beforeAll`, but the population of the meta-inf-registry happens inside `beforeAll`.
=> Constraint example validation test

libs/interpreter-lib/src/parsing-util.ts, libs/language-server/src/lib/builtin-library/jayvee-standard-library.ts
Partially addresses #397 
Executing with a  reference to `Percent` of the standard library works
Clicking on a reference to `Percent` allows jumping to a read-only version of the `standard.jv`
- auto-complete
- organize standard.jv in multiple jv files
=> Init standard library

libs/execution/src/lib/blocks/execution-result.ts, libs/extensions/std/exec/src/http-extractor-executor.ts, libs/extensions/std/exec/src/util/backoff-strategy.spec.ts, libs/extensions/std/exec/src/util/backoff-strategy.ts, libs/extensions/std/lang/src/http-extractor-meta-inf.ts
Closes #403.
```
block CarsExtractor oftype HttpExtractor {
url: "https://gist.githubusercontent.com/noamross/e5dasdasd..."; // invalid URL
retries: 3;
retryBackoff: 10000;
}
```
=> Implement Retry Mechanism for HttpExtractor

libs/execution/src/lib/execution-context.ts
Fixed an issue that prevented the retrieval of default property values of constraint definitions
=> Fixed constraint default property value retrieval

libs/language-server/src/stdlib/CSVExtractor.jv, libs/language-server/src/stdlib/GTFSExtractor.jv
This PR adds a CSVExtractor and a GTFSExtractor to the stdlib. However, they are not part of the autocomplete suggestions of the VSCode extension. The same is true for the Percentage valuetype though so I assume this is as expected for now, right @georg-schwarz ?
Part of #217
=> Added CSVExtractor and GTFSExtractor to stdlib

apps/vs-code-extension/src/standard-library-file-system-provider.ts, libs/execution/src/lib/constraints/constraint-executor-registry.ts, libs/interpreter-lib/src/validation-checks/runtime-parameter-literal.ts, libs/language-server/src/grammar/constraint.langium, libs/language-server/src/grammar/main.langium, libs/language-server/src/grammar/terminal.langium, libs/language-server/src/lib/ast/expressions/internal-value-representation.ts, libs/language-server/src/lib/builtin-library/stdlib.ts, libs/language-server/src/lib/completion/jayvee-completion-provider.ts, libs/language-server/src/lib/hover/jayvee-hover-provider.ts, libs/language-server/src/lib/meta-information/meta-inf-registry.ts, libs/language-server/src/lib/validation/checks/typed-constraint-definition.ts, libs/language-server/src/lib/validation/checks/valuetype-reference.ts
This mechanism is similar to the current jv code generation to self-document blocktypes.
Exerpt:
I noticed some issue with Jayvee having no concept for INFINITY. Still, I'd vote to integrate this feature nevertheless.
=> Document Constraint Types in Code

libs/interpreter-lib/src/validation-checks/runtime-parameter-literal.spec.ts, libs/interpreter-lib/test/assets/runtime-parameter-literal/valid-integer-runtime-property.jv, libs/interpreter-lib/test/assets/runtime-parameter-literal/valid-text-runtime-property.jv
Part of #420
Added simple tests for `validateRuntimeParameterLiteral`
=> runtime-parameter-literal tests

apps/interpreter/src/examples-smoke-test.spec.ts, libs/execution/test/utils.ts
Fixed tests that stub `process.exit` to exit the tested method while not exiting test altogether.
=> Fixed `process.exit` not exiting tested method

libs/extensions/std/exec/src/text-range-selector-executor.ts, libs/extensions/std/lang/src/text-range-selector-meta-inf.ts, libs/language-server/src/lib/ast/wrappers/cell-range-wrapper.ts, libs/language-server/src/lib/constraint/length-constraint-meta-inf.ts, libs/language-server/src/lib/constraint/range-constraint-meta-inf.ts
Replaced Number.POSITIVE_INFINITY and Number.NEGATIVE_INFINITY with Number.MAX_SAFE_INTEGER and Number.MIN_SAFE_INTEGER due to `Number.isInteger(Number.POSITIVE_INFINITY)` returning `false`
=> Infinity number parsing fix

libs/interpreter-lib/src/parsing-util.spec.ts, libs/interpreter-lib/src/validation-checks/runtime-parameter-literal.spec.ts, libs/interpreter-lib/test/assets/parsing-util/validateDocument/valid-simplify-warning.jv, libs/interpreter-lib/test/assets/runtime-parameter-literal/test-extension/TestBlockTypes.jv, libs/language-server/src/lib/validation/checks/blocktype-definition.ts
This PR fixes a few issues with the builtin blocktype definitions:
- [libs/language-server/src/lib/validation/checks/blocktype-definition.ts:](https://github.com/jvalue/jayvee/blob/128ffac73c5449f8752ea69e0826b7b7ea447813/libs/language-server/src/lib/validation/checks/blocktype-definition.ts) Fixed `checkPropertyDefaultValuesHasCorrectType` wrongly passing valuetype reference to `createValuetype` instead of valuetype itself
- Replaced `process.cwd()` with `path.resolve(__dirname, )` to make tests independant of working directory
- Added missing test blocktype definitions
=> Builtin blocktype definition bug fixes

libs/interpreter-lib/src/parsing-util.spec.ts, libs/interpreter-lib/src/validation-checks/runtime-parameter-literal.spec.ts, libs/language-server/src/test/utils.ts
Extracted the `initializeWorkspace` for test extension loading into a correspondingly named utils function for easier understanding
=> LoadTestExtensions utils function

apps/docs/project.json, apps/interpreter/project.json, apps/vs-code-extension/project.json, libs/interpreter-lib/project.json, libs/language-server/project.json, libs/monaco-editor/project.json, tools/scripts/interpreter/prepend-shebang.mjs
Before the fix, we executed all commands in nx jobs parallel.
This led to some issues in packaging, e.g. closes #465.
Adding the flag `"parallel": false` in all locations ensures that this issue will not be introduced by mistake again (e.g., by adding another script to an nx job)
=> Execute all commands in nx jobs sequentially

libs/execution/src/lib/types/io-types/table.ts
As discussed in https://github.com/jvalue/jayvee/pull/458#issuecomment-1790507847
This PR fixes the issue that the `numberOfRows` of a `Table` is incremented during `addRow` if the table contains no columns and the length of the row to be added is 0.
This causes the table to indicate that it contains data (because `table.getNumberOfRows() > 0`) without containing any data.
**Note: Currently this is only documented using jsdoc (and the comments/PRs in GitHub).**
=> Table numberOfRows increment on no columns

rfc/0015-multi-file-jayvee/0015-multi-file-jayvee.md
This PR is a reissue of https://github.com/jvalue/jayvee/pull/474.
Introduce concepts to enable multi-file Jayvee: 
- `publish` elements of a jv file for reuse in other files of the same project
- `libraries` for bundling elements for reuse in other projects
- `use` of elements and libraries in other files / projects
=> [RFC] Publish and Use: Elements and Libraries

libs/language-server/src/grammar/block.langium, libs/language-server/src/grammar/blocktype.langium, libs/language-server/src/grammar/main.langium, libs/language-server/src/grammar/pipeline.langium
For the sake of navigability, every language concept should have its own file.
=> Distribute pipeline and block grammar to separate files

libs/execution/src/lib/types/valuetypes/internal-representation-parsing.ts
Allows parsing numbers in scientific notation, both integers like 1.904761905e+20 or decimals like 8.1e-5.
Closes https://github.com/jvalue/jayvee/issues/488
=> Adapted number regex to allow scientific notation

apps/interpreter/src/index.ts, apps/interpreter/src/parse-only.spec.ts, apps/interpreter/src/run-action.ts, apps/interpreter/test/assets/broken-model.jv, libs/interpreter-lib/src/interpreter.ts
This PR adds a `--parse-only` flag to the interpreter. Using this flag, the app just parses (and therefore validates) the given Jayvee model without executing it.
The process (when called with `--parse-only`) ends with `0` in case of valid model, with `1` otherwise.
=> Add `--parse-only` flag

apps/docs/docs/dev/03-architecture-overview.md
I repeatedly noticed that the relation of the grammar specification (langium files) and the generated TS interfaces and guard functions is not well-documented until now.
This is an attempt to improve it. Please let me know if you see a better place where to put it.
=> Document relation of Langium files and AST TypeScript files

example/gtfs-static.jv, libs/execution/src/lib/blocks/block-execution-util.ts, libs/execution/src/lib/blocks/composite-block-executor.ts, libs/interpreter-lib/src/interpreter.ts, libs/language-server/src/lib/ast/model-util.ts, libs/language-server/src/lib/ast/wrappers/index.ts, libs/language-server/src/lib/ast/wrappers/pipeline-wrapper.ts, libs/language-server/src/lib/validation/checks/block-definition.ts, libs/language-server/src/lib/validation/checks/pipeline-definition.spec.ts, libs/language-server/src/lib/validation/checks/pipeline-definition.ts, libs/language-server/src/test/assets/pipeline-definition/invalid-pipeline-only-blocks.jv, libs/language-server/src/test/assets/pipeline-definition/valid-pipeline.jv
Until now, we have navigated over all blocks within a pipeline and connected them via pipes to get our execution order.
However, #485 will change that by allowing block definitions outside of pipelines, raising the necessity to iterate purely over the pipes with a pipeline.
This PR introduces a `PipelineWrapper` in the already existing of `AstNodeWrapper`s that inhibits the functionality to navigate over a pipeline and replaces the existing helper methods in the `model-util`.
The PR should not change the behavior of Jayvee besides:
- Pipelines with one block but no pipes were previously valid, which is not the case anymore (see adapted tests).
=> Navigate Pipeline via Pipes instead of Blocks

libs/language-server/src/lib/validation/checks/block-definition.spec.ts, libs/language-server/src/lib/validation/checks/block-definition.ts, libs/language-server/src/lib/validation/checks/composite-blocktype-definition.spec.ts, libs/language-server/src/lib/validation/checks/composite-blocktype-definition.ts, libs/language-server/src/lib/validation/checks/pipeline-definition.spec.ts, libs/language-server/src/lib/validation/checks/pipeline-definition.ts, libs/language-server/src/test/assets/composite-blocktype-definition/invalid-block-as-multiple-pipe-inputs.jv, libs/language-server/src/test/assets/composite-blocktype-definition/invalid-composite-blocktype-multiple-pipelines.jv, libs/language-server/src/test/assets/pipeline-definition/invalid-block-as-multiple-pipe-inputs.jv
- Changed logic to iterate over pipeline structure.
- Adapted some tests to be more precise
Validation output should have stayed roughly the same (except some minor edge cases)
=> Refactor block validation multiple pipe inputs

README.md
We should share our roadmap and vision of Jayvee with the world.
See the rendered README [here](https://github.com/jvalue/jayvee/tree/document-roadmap)
=> Add roadmap section to the README

libs/language-server/src/lib/completion/jayvee-completion-provider.ts, package-lock.json, package.json
Closes #426.
- Upgrade Langium to version `1.3`
- Upgrade TypeScript to version `4.9.5` as the new langium version introduces the usage of the `satisfies` keyword that comes with TypeScript version `4.9.0`.
- Fix the `JayveeCompletionProvider` that needs to be handed through the `CompletionContext` (change in the new Langium version)
- Further, upgrade TypeScript to `5.0.4` - the version Langium version `1.3` used for development; in expectation the future versions require upgrading TypeScript anyway
=> Upgrade to Langium 1.3

tools/scripts/relax-peer-dependency-versions.mjs
Publishing jayvee fails with
```
Found no peer dependencies in package.json
Warning: run-commands command "node tools/scripts/relax-peer-dependency-versions.mjs interpreter-lib" exited with non-zero status code
```
And I don't think there are peer dependencies in the package.json indeed, could this be related to the upgrades (langium/nx)?
This change allows all steps including `pack` to run successfully at least.
=> Fixed build failing if no peer dependencies exist

.github/workflows/check-paths-for-windows.yaml, tools/scripts/monaco-editor/delete-vscode-peer-dependency.mjs, tools/scripts/monaco-editor/relax-react-version.mjs
I am not sure why this did not fail earlier for me but this allows pack to run for all projects, using `npx nx run-many --target pack`. As this only changes the monaco editor used in the hub the impact should be small.
=> Fixed publishing to npm failing because of peerDependencies

libs/language-server/src/lib/ast/expressions/evaluators/replace-operator-evaluator.spec.ts, libs/language-server/src/lib/ast/expressions/test-utils.ts
Adds basic test utilities (reusing transforms) and uses those to implement a few example operator tests for expressions.
reference https://github.com/jvalue/jayvee/issues/522
=> Operator tests

.github/workflows/ci.yaml, apps/interpreter/project.json, apps/language-server-web-worker/project.json, libs/interpreter-lib/project.json, libs/language-server/project.json, libs/monaco-editor/project.json, tools/scripts/publish.mjs
Adds a "package publish dry-run" to every CI run to ensure releases don't fail due to build errors. 
I used the `pre-publish` build command instead of introducing another command.
=> CI Publish Safeguard

apps/docs/docs/user/expressions.md, libs/language-server/src/grammar/expression.langium, libs/language-server/src/lib/ast/expressions/evaluators/lowercase-operator-evaluator.spec.ts, libs/language-server/src/lib/ast/expressions/evaluators/lowercase-operator-evaluator.ts, libs/language-server/src/lib/ast/expressions/evaluators/uppercase-operator-evaluator.spec.ts, libs/language-server/src/lib/ast/expressions/evaluators/uppercase-operator-evaluator.ts, libs/language-server/src/lib/ast/expressions/operator-registry.ts, libs/language-server/src/lib/ast/expressions/type-computers/string-transform-type-computer.ts
adds the `lowercase` and  `lowercase` operators.
I adapted `cars.jv* to demonstrate them. This file adds 2 new columns, one for the lowercase and one for the uppercase name.
```
pipeline CarsPipeline {
CarsExtractor
-> CarsTextFileInterpreter
-> CarsCSVInterpreter
-> NameHeaderWriter
-> CarsTableInterpreter
-> NameToLowerCase
-> NameToUpperCase
-> CarsLoader;
block CarsExtractor oftype HttpExtractor {
url: "https://gist.githubusercontent.com/noamross/e5d3e859aa0c794be10b/raw/b999fb4425b54c63cab088c0ce2c0d6ce961a563/cars.csv";
}
block CarsTextFileInterpreter oftype TextFileInterpreter { }
block CarsCSVInterpreter oftype CSVInterpreter {
enclosing: '"';
}
block NameHeaderWriter oftype CellWriter {
at: cell A1;
write: ["name"];
}
block CarsTableInterpreter oftype TableInterpreter {
header: …
```
=> add unary operators 'lowercase' and 'uppercase'

libs/execution/src/lib/blocks/block-executor.ts, libs/execution/src/lib/debugging/debug-log-visitor.ts, libs/extensions/tabular/exec/src/lib/cell-range-selector-executor.ts, libs/extensions/tabular/exec/src/lib/cell-writer-executor.ts, libs/extensions/tabular/exec/src/lib/column-deleter-executor.ts, libs/extensions/tabular/exec/src/lib/row-deleter-executor.ts, libs/interpreter-lib/src/interpreter.ts, libs/language-server/src/lib/ast/expressions/evaluate-expression.ts, libs/language-server/src/lib/ast/expressions/index.ts, libs/language-server/src/lib/ast/expressions/internal-value-representation.ts, libs/language-server/src/lib/ast/wrappers/value-type/primitive/cell-range-value-type.ts, libs/language-server/src/lib/validation/checks/block-type-specific/property-assignment.ts, libs/language-server/src/lib/validation/checks/block-type-specific/property-body.ts, libs/language-server/src/lib/validation/validation-util.ts
Removes a dependency cycle from our code base by using the `WrapperFactoryProvider` construct introduced in #536.
The remaining dependency cycles revolve around our design of the `ValueType` and `wrapper` constructs.
=> Remove dependency cycle caused be CellRangeWrapper being an internal value representation

libs/execution/src/lib/types/io-types/filesystem-inmemory.ts, libs/extensions/std/exec/src/file-picker-executor.spec.ts, libs/extensions/std/exec/test/assets/file-picker-executor/dot-valid-file-picker.jv
paths inside `FilePicker` can now start with a dot
```
block DataPicker oftype FilePicker {
path: "./data.csv";
}
```
closes #381
=> fix(FilePicker): path can now start with a dot

libs/execution/src/lib/constraints/executors/length-constraint-executor.spec.ts, libs/execution/src/lib/constraints/executors/range-constraint-executor.spec.ts, libs/execution/test/assets/length-constraint-executor/only-lower-bound.jv, libs/execution/test/assets/length-constraint-executor/only-upper-bound.jv, libs/execution/test/assets/range-constraint-executor/only-lower-bound.jv, libs/execution/test/assets/range-constraint-executor/only-upper-bound.jv, libs/language-server/src/lib/validation/checks/constrainttype-specific/property-body.spec.ts, libs/language-server/src/lib/validation/checks/constrainttype-specific/property-body.ts, libs/language-server/src/test/assets/property-body/constrainttype-specific/length-constraint/no-bound.jv, libs/language-server/src/test/assets/property-body/constrainttype-specific/range-constraint/no-bound.jv
It is now possible to only specify one bound when using `lenght-constraint`. However one bound minimum is still required
closes #533
I went ahead and took the liberty to also implement this fix for `range-constraint`.
=> fix: range-constraint and lenght-constraint work with only one bound

libs/execution/src/lib/types/value-types/internal-representation-parsing.ts, libs/extensions/tabular/exec/test/assets/table-transformer-executor/valid-column-type-change.jv, libs/language-server/src/grammar/expression.langium, libs/language-server/src/lib/ast/expressions/evaluators/parse-operators-evaluators.spec.ts, libs/language-server/src/lib/ast/expressions/evaluators/parse-operators-evaluators.ts, libs/language-server/src/lib/ast/expressions/operator-registry.ts, libs/language-server/src/lib/ast/expressions/type-computers/parse-opterators-type-computer.ts, libs/language-server/src/lib/ast/expressions/typeguards.ts, libs/language-server/src/lib/ast/wrappers/value-type/primitive/boolean-value-type.ts, libs/language-server/src/lib/ast/wrappers/value-type/primitive/decimal-value-type.ts, libs/language-server/src/lib/ast/wrappers/value-type/primitive/integer-value-type.ts, libs/language-server/src/lib/ast/wrappers/value-type/primitive/primitive-value-type.ts, libs/language-server/src/lib/ast/wrappers/value-type/primitive/text-value-type.ts, libs/language-server/src/lib/jayvee-module.ts
This PR allows to parse `text` into the builtin primitives `decimal`, `integer` and `boolean`
example file:
```
pipeline CarsPipeline {
CarsExtractor -> CarsTextFileInterpreter;
CarsTextFileInterpreter
-> CarsCSVInterpreter
-> NameHeaderWriter
-> CarsTableInterpreter
-> DispTransform
-> HpTransform
-> CarsLoader;
block CarsExtractor oftype HttpExtractor {
url: "https://gist.githubusercontent.com/noamross/e5d3e859aa0c794be10b/raw/b999fb4425b54c63cab088c0ce2c0d6ce961a563/cars.csv";
}
block CarsTextFileInterpreter oftype TextFileInterpreter { }
block CarsCSVInterpreter oftype CSVInterpreter {
enclosing: '"';
}
block NameHeaderWriter oftype CellWriter {
at: cell A1;
write: ["name"];
}
block CarsTableInterpreter oftype TableInterpreter {
header: true;
columns: [
"name" oftype text,
"mpg" …
```
=> feat: enable transforming of value types

libs/language-server/src/lib/jayvee-module.ts, libs/language-server/src/lib/lsp/index.ts, libs/language-server/src/lib/lsp/jayvee-code-action-provider.ts, libs/language-server/src/lib/lsp/jayvee-completion-provider.ts, libs/language-server/src/lib/lsp/jayvee-definition-provider.ts
Builds on #564 - so merge that one first and rebase!
- path completion based on files in fs
- jump to file when clicking on import path
- import action if not defined element exists in another file
=> Import Code Actions

libs/language-server/src/grammar/main.langium, libs/language-server/src/lib/lsp/jayvee-scope-provider.ts, libs/language-server/src/lib/validation/checks/export-definition.spec.ts, libs/language-server/src/lib/validation/checks/export-definition.ts, libs/language-server/src/lib/validation/validation-registry.ts, libs/language-server/src/test/assets/export-definition/invalid-export-definition-on-exported-element.jv, libs/language-server/src/test/assets/export-definition/invalid-export-definition-same-name-exported-definition.jv, libs/language-server/src/test/assets/export-definition/invalid-export-definition-same-name-multiple-alias.jv, libs/language-server/src/test/assets/export-definition/valid-export-definition-no-alias.jv, libs/language-server/src/test/assets/export-definition/valid-export-definition-with-alias.jv
Builds on #571. Introduces `export Element as Alias;` syntax.
=> Publish via alias

apps/docs/docs/user/core-concepts.md, example/electric-vehicles.jv, example/state-codes.jv
=> Document publish use feature

libs/language-server/project.json
The language service does not generate code from the langium definitions automatically. This bug was introduced during the changes to the build system in #558 / 05f47bfc55ec213193685cb4dd8754a37c6445cd.
=> Add generate task as build dependency

apps/interpreter/project.json, nx.json
Sourcemaps help debugging, especially when editing the interpreter. The sourcemaps are only emitted when building explicitly with the configuration `development`. This is enabled by default when running the examples. 
Before (References compiled and bundled JS code):
```
file:///path/to/jayvee/dist/apps/interpreter/main.js:14606
throw new Error("TEST");
^
Error: TEST
at file:///path/to/jayvee/dist/apps/interpreter/main.js:14606:7
at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
at async loadESM (node:internal/process/esm_loader:34:7)
at async handleMainPromise (node:internal/modules/run_main:113:12)
```
After (References TypeScript source):
```
/path/to/jayvee/libs/interpreter-lib/src/index.ts:10
throw …
```
=> Add sourcemaps to development build

.github/workflows/ci.yaml
CI is buggy. This most probably is due to the parallel execution
=> [CI] Remove parallel execution and add verbose logging

.github/workflows/ci.yaml
#586 did not properly work since the default is running 3 tasks in parallel. Setting this explicitly to 1 fixes this.
=> [CI] Remove parallel execution

apps/interpreter/src/examples-smoke-test.spec.ts, apps/interpreter/src/index.ts, apps/interpreter/src/parse-only.spec.ts, apps/interpreter/src/run-action.ts, apps/interpreter/src/run-options.ts, libs/interpreter-lib/src/interpreter.spec.ts, libs/interpreter-lib/src/interpreter.ts, libs/interpreter-lib/src/parsing-util.ts
- reduces amounts of parameters in the interpretation model by using object construction
- defines a nicer interpreter interface that is easier to use
- pulls out CLI runtime argument validation (should not be located in interpreter-lib)
- introduces a default value for the `--debug-target` parameter to align with other params: use a default value over undefined
=> Refactor Interpreter (to an Interface + Implementation Class)

apps/docs/docs/user/examples/README.mdx, apps/docs/docs/user/use-cases/README.mdx, apps/docs/docs/user/use-cases/README.mdx.license, apps/docs/docs/user/use-cases/SWC-JValue-OCDE-Case1.md, apps/docs/docs/user/use-cases/SWC-JValue-OCDE-Case1.md.license
Adds a reference to use cases to the docs, currently only with the SWC project. I'd keep the actual description of the use case on the shorter side and directly link to the GitHub repo as I think it is pretty well explained there.
I will of course not merge this PR before making the SWC examples repo public.
=> Add link to SWC example to docs

nx.json
The `README.md`s were in the wrong directory in the build output. This PR fixes which also makes the NPM page proper again (https://www.npmjs.com/package/@jvalue/jayvee-interpreter-lib).
Before:
```
interpreter-lib/
├── libs
│   └── interpreter-lib
│       └── README.md
├── main.js
├── package.json
└── package-lock.json
```
With these changes:
```
interpreter-lib/
├── main.js
├── package.json
├── package-lock.json
└── README.md
```
=> Fix README output

libs/language-server/package.json
The entry point to the `language-server` lib is wrong. Removing the attribute allows `esbuild` to set it automatically to the correct value `./main.js`
=> Remove explicit main attribute

libs/extensions/std/exec/src/local-file-extractor-executor.spec.ts, libs/extensions/std/exec/src/local-file-extractor-executor.ts
Problem: no matter why `readFile()` fails, the error is reported as 'file not found'
Solution: print the thrown errors message
closes #609
=> fix(LocalFileExtractor): log correct error message

libs/interpreter-lib/src/parsing-util.ts, package-lock.json, package.json
=> Fix windows filepaths

.gitignore, libs/execution/src/lib/blocks/block-execution-util.ts, libs/execution/src/lib/blocks/block-executor.ts, libs/execution/src/lib/execution-context.ts, libs/execution/src/lib/hooks/hook-context.ts, libs/execution/src/lib/hooks/hook.ts, libs/execution/src/lib/hooks/index.ts, libs/execution/src/lib/index.ts, libs/interpreter-lib/src/interpreter.spec.ts, libs/interpreter-lib/src/interpreter.ts, libs/interpreter-lib/test/assets/hooks/valid-builtin-and-composite-blocks.jv
Closes #633.
This PR adds hook  functionality to the Jayvee interpreter. Hooks are custom functions that are automatically executed before / after blocks. See the `PreBlockHook` and `PostBlockHook` types for such a functions signature.
Library users can add hooks with the `addHook` method:
```typescript
const program = /* parse program ...*/;
const before: PreBlockHook = (blocktype, input, context) => { /* ... */ };
program.addHook('preBlock', before, { blocking: true });
const after: PostBlockHook = (blocktype, input, context, output) => { /* ... */ };
program.addHook('postBlock', after);  // Options can be omitted. Non-blocking is the default
const blockSpecificHook = (blocktype, input, context) => { /* ... */ };
myJayveeProgram.addHook('preBlock', blockSpecificHook, {
blocktypes: …
```
=> [FEATURE] Add custom hook support

libs/execution/src/lib/blocks/block-execution-util.ts, libs/execution/src/lib/hooks/hook-context.ts
Closes #637.
This PR adds the hook duration to the debug logger. This is the same level as block duration logging.
=> [FEATURE] Include hooks in time measurement of blocks

libs/execution/src/lib/execution-context.ts, libs/execution/src/lib/hooks/hook-context.ts, libs/execution/src/lib/hooks/hook.ts, libs/interpreter-lib/src/interpreter.spec.ts
This PR changes the hook's signature to only receive one object with the previous parameter as properties. This has the following advantages:
- Backwards compatibility: Adding new "parameters" at whatever position doesn't break existing code
- It's easier to ignore unused "parameters".
Depends on #638.
=> [REFRACTOR] Hooks recieve a single parameter

apps/docs/docs/user/intro/intro.mdx
Closes #550.
This PR extends the user documentation with information about the [jayvee neovim plugin](https://github.com/jvalue/jayvee.nvim) and general information on how to use Jayvee with Neovim.
=> Mention neovim extension in the docs

libs/execution/src/lib/debugging/debug-log-visitor.ts, libs/execution/src/lib/util/index.ts, libs/execution/src/lib/util/string-util.spec.ts, libs/execution/src/lib/util/string-util.ts, libs/extensions/std/exec/src/text-line-deleter-executor.spec.ts, libs/extensions/std/exec/src/text-line-deleter-executor.ts, libs/extensions/std/exec/src/text-range-selector-executor.ts
**Problem**: When chaining `TextRangeSelector` and `TextLineDeleter` the following happens:
```typescript
// TextRangeSelector
let lines = splitLines(file.content);
let newLines = /* ... select range ... */;
return new TextFile(newLines.join());
// ...
// TextLineDeleter
let lines = splitLines(file.content);
let newLines = /* ... deleteLines ... */;
return new TextFile(newLines.join());
```
This might mean a lot of "useless" splits and joins, which becomes especially problematic for large files.
**Solution**: Introduce the new util function `findLineBounds()`. This function takes a sorted array of line indices, a regex to find line breaks and the text as parameters. It maps each line index to the start of the line and its length, stopping at the first non existent line index.
I didn't …
=> [PERF] Don't split and join lines when using `TextFile`

libs/execution/src/lib/types/io-types/table.ts, libs/extensions/rdbms/exec/src/lib/postgres-loader-executor.spec.ts, libs/extensions/rdbms/exec/src/lib/postgres-loader-executor.ts, libs/extensions/rdbms/exec/src/lib/sqlite-loader-executor.spec.ts, libs/extensions/rdbms/exec/src/lib/sqlite-loader-executor.ts, package.json
Closes #641.
This PR enables `SQLiteLoader` and `PostresLoader` to handle column names with quotes. 
Column names are now converted to SQL with the same mechanism as cell values (using a visitor).
It depends on #647, so I've marked this as a draft until the previous PR gets merged.
=> [BUG] Handle column names that include double quotes

libs/execution/src/lib/blocks/block-execution-util.ts, libs/execution/src/lib/index.ts, libs/execution/src/lib/perf.ts, libs/interpreter-lib/src/interpreter.ts
Currently, Jayvee uses [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)  to measure the duration of hooks, blocks and pipelines.
With this PR, the Jayvee interpreter now sets ["performance marks"](https://nodejs.org/api/perf_hooks.html) at relevant points during execution (before/after blocks/pipelines) and then measures the time between these marks. For now, marks are named with the following schema, with the goal of "encoding" the mark's location in the name:
```
`${pipeline name}::${block name}::${preBlockHook or BlockExecution or postBlockHook}::{start or end}`
```
This isn't final though, and I other ideas are welcome.
IMO this is a better approach than using the standard Jayvee hooks. Quoting …
=> Replace `Date` with `perf-hooks` for time measurement

.github/workflows/ci.yaml, apps/benchmark/.eslintrc.json, apps/benchmark/.eslintrc.json.license, apps/benchmark/package.json, apps/benchmark/package.json.license, apps/benchmark/project.json, apps/benchmark/project.json.license, apps/benchmark/src/benchmark-dummy-test.spec.ts, apps/benchmark/src/benchmark_definitions.json, apps/benchmark/src/benchmark_definitions.json.license, apps/benchmark/src/calc.ts, apps/benchmark/src/index.ts, apps/benchmark/src/run.ts, apps/benchmark/src/runModels.ts, apps/benchmark/tsconfig.app.json, apps/benchmark/tsconfig.app.json.license, apps/benchmark/tsconfig.json, apps/benchmark/tsconfig.json.license, apps/benchmark/tsconfig.spec.json, apps/benchmark/tsconfig.spec.json.license, apps/benchmark/vite.config.ts, apps/interpreter/src/parse-only.spec.ts, libs/execution/src/lib/blocks/block-execution-util.ts, libs/execution/src/lib/perf.ts, libs/extensions/tabular/exec/src/lib/table-interpreter-executor.ts, libs/interpreter-lib/src/interpreter.ts, package.json
Depends on #649.
This PR implements a simple benchmarking tool (`npm run benchmark`) and adds a CI step to verify that no performance regression is introduced.
Benchmarks are specified in `apps/benchmark/src/benchmark_definitions.json`. For now, only the total pipeline duration is tested.
Failed benchmark step: https://github.com/jvalue/jayvee/actions/runs/14313480465/job/40113976972
=> Add benchmarking into the CI

apps/benchmark/src/run.ts, apps/interpreter/src/examples-smoke-test.spec.ts, apps/interpreter/src/index.ts, apps/interpreter/src/parse-only.spec.ts, apps/interpreter/src/run-action.ts, apps/interpreter/src/run-options.ts, libs/execution/src/lib/blocks/block-execution-util.ts, libs/execution/src/lib/blocks/block-executor.ts, libs/execution/src/lib/blocks/composite-block-executor.ts, libs/execution/src/lib/util/index.ts, libs/execution/src/lib/util/mermaid-util.spec.ts, libs/execution/src/lib/util/mermaid-util.ts, libs/interpreter-lib/src/interpreter.spec.ts, libs/interpreter-lib/src/interpreter.ts, libs/interpreter-lib/test/assets/graph/composite-block.jv, libs/interpreter-lib/test/assets/graph/two-pipelines.jv, package.json
Continues #517
This PR adds a new flag for the Jayvee interpreter `-g`/`--graph`. With this flag, the interpreter parses the model and generates a mermaid.js flowchart.
TODO:
Followup PRs:
- Implement block-specific nodes
- use class definitions
- Also display the initial input value in the graph. This means adding the parameter `initialInputValue: IOTypeImplementation | undefined = undefined` to `executionGraph()`
- Support more config options like `style` and `theme`
=> [FEATURE] Generate mermaid.js syntax from a model

apps/benchmark/src/benchmark_definitions.json
The CI fails because of the benchmarks. The execution speed hasn't changed significantly since creation, the 30ms duration was just a bit too optimistic.
=> Update benchmark duration for cars from 30ms to 45ms

rfc/0014-attribute-based-valuetypes/README.md
I think we didn't integrate some change proposals we agreed on. This PR introduces those changes.
=> Incorporate missing change proposals to RFC 00014

.editorconfig, .prettierrc.js, .prettierrc.json, .prettierrc.json.license
This PR introduces an EditorConfig file, which allows [many editors](https://editorconfig.org/#pre-installed) to indent files correctly.
Additionally prettier's javascript config is replaced with a much simpler json.
=> Introduce .editorconfig and replace prettier's js config file with json

example/electric-vehicles.jv, libs/interpreter-lib/test/assets/graph/two-pipelines.jv, libs/language-server/src/grammar/expression.langium, libs/language-server/src/lib/ast/expressions/evaluation-context.ts, libs/language-server/src/lib/ast/expressions/evaluators/lengthof-operator-evaluator.spec.ts, libs/language-server/src/lib/ast/expressions/evaluators/lengthof-operator-evaluator.ts, libs/language-server/src/lib/ast/expressions/operator-registry.ts, libs/language-server/src/lib/ast/expressions/test-utils.ts, libs/language-server/src/lib/ast/expressions/type-computers/lengthof-operator-type-computer.ts, libs/language-server/src/lib/ast/expressions/type-inference.ts, libs/language-server/src/lib/ast/expressions/typeguards.ts, libs/language-server/src/test/assets/constraint-definition/invalid-incompatible-type.jv, libs/language-server/src/test/assets/constraint-definition/valid-simplify-info.jv, libs/language-server/src/test/assets/constraint-definition/valid-text-constraint.jv, libs/language-server/src/test/assets/jayvee-model/invalid-non-unique-constraints.jv
This PR replaces the existing syntax
```
constraint ExactlyTenCharacters on text: value.length == 10;
```
with
```
constraint ExactlyTenCharacters on text: lengthof value == 10;
```
This allows lengths of any string, collection or reference to either to be calculated, not just `value`.
=> Replace length access with operator

libs/language-server/src/lib/ast/expressions/evaluators/equality-operator-evaluator.spec.ts, libs/language-server/src/lib/ast/expressions/evaluators/equality-operator-evaluator.ts, libs/language-server/src/lib/ast/expressions/evaluators/inequality-operator-evaluator.spec.ts, libs/language-server/src/lib/ast/expressions/evaluators/inequality-operator-evaluator.ts, libs/language-server/src/lib/ast/expressions/test-utils.ts
Problem: Comparing an erroneous values with `invalid` returns false, when it should return true
Solution: Update implementations of `EqualityOperatorEvaluator` and `InequalityOperatorEvaluator`
=> Correct comparison for error values
